### ISSUE TITLE
漫画自适应屏幕高度的功能希望能做成可选开启

### ISSUE THREAD

**Issue by heptaspirit** [Byaidu/dmzj-helper#1]
问题：部分长条漫画单页长度过长，自适应屏幕高度后会无法观看
示例：https://manhua.dmzj1.com/jiaoshizhengbasai/114359.shtml

希望能把自适应浏览器高度的功能做成可选开启，对于类似于问题中的页面也能手动适应。

**Comment by Byaidu** [comment]
已更新4.0版本，可以在单页模式下正常看长条漫
